import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'dart:math';
import '../main_layout.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:open_file/open_file.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
class FeesScreen extends StatefulWidget {
  const FeesScreen({super.key});

  @override
  State<FeesScreen> createState() => _FeesScreenState();
}

class _FeesScreenState extends State<FeesScreen> {
  Map<String, dynamic>? _mockData;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    final String jsonString = await rootBundle.loadString('assets/mock/fees_overview.json');
    setState(() {
      _mockData = json.decode(jsonString);
    });
  }

  Future<void> _simulateDownload(String itemName) async {
    // Show downloading dialog
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) {
        return Dialog(
          backgroundColor: Colors.white,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const SizedBox(
                  width: 24,
                  height: 24,
                  child: CircularProgressIndicator(color: Color(0xFF6C4CF1), strokeWidth: 3),
                ),
                const SizedBox(width: 20),
                Expanded(child: Text('Generating $itemName...', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF1E1E2D)))),
              ],
            ),
          ),
        );
      },
    );

    try {
      // 1. Generate PDF
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Center(
              child: pw.Column(
                mainAxisAlignment: pw.MainAxisAlignment.center,
                children: [
                  pw.Text('Receipt / Invoice', style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 20),
                  pw.Text(itemName, style: const pw.TextStyle(fontSize: 24)),
                  pw.SizedBox(height: 40),
                  pw.Text('Generated by Parent App on ${DateTime.now().toString().split('.')[0]}', style: const pw.TextStyle(fontSize: 14)),
                ],
              ),
            );
          },
        ),
      );

      // Fake delay for realistic feel
      await Future.delayed(const Duration(seconds: 1));

      // 2. Save file
      Directory? dir;
      if (Platform.isAndroid) {
        // Use external storage for Android so it goes to real Downloads or Documents
        dir = await getExternalStorageDirectory();
      } else {
        dir = await getApplicationDocumentsDirectory();
      }
      
      if (dir == null) throw Exception("Could not find directory to save file");
      
      final String safeName = itemName.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
      final String filePath = '${dir.path}/$safeName.pdf';
      final file = File(filePath);
      await file.writeAsBytes(await pdf.save());

      // Close dialog
      if (mounted) Navigator.pop(context);
      
      // Show success snackbar with Open button
      if (mounted) {
        ScaffoldMessenger.of(context).clearSnackBars();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.check_circle_outline, color: Colors.white),
                const SizedBox(width: 12),
                const Expanded(child: Text('Saved as PDF successfully!', style: TextStyle(fontWeight: FontWeight.bold))),
              ],
            ),
            action: SnackBarAction(
              label: 'OPEN',
              textColor: Colors.white,
              onPressed: () {
                OpenFile.open(filePath);
              },
            ),
            backgroundColor: const Color(0xFF4CAF50),
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
            margin: const EdgeInsets.all(20),
            duration: const Duration(seconds: 2), // Reduced duration
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // close dialog
        ScaffoldMessenger.of(context).clearSnackBars();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to download: $e'),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 2), // Reduced duration
          )
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_mockData == null) {
      return const Center(child: CircularProgressIndicator(color: Color(0xFF6C4CF1)));
    }

    final data = _mockData!;

    return ValueListenableBuilder<String>(
      valueListenable: MainLayout.globalSearchQuery,
      builder: (context, searchQuery, child) {
        final query = searchQuery.toLowerCase();

        if (query.isNotEmpty) {
          // Filter upcoming payments and history
          final upcoming = (data['upcomingPayments'] as List? ?? []).where((p) =>
            p['title'].toString().toLowerCase().contains(query) ||
            (p['category'] ?? '').toString().toLowerCase().contains(query)
          ).toList();
          final history = (data['paymentHistory'] as List? ?? []).where((p) =>
            p['title'].toString().toLowerCase().contains(query) ||
            (p['category'] ?? '').toString().toLowerCase().contains(query)
          ).toList();

          return SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 20.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(height: 12),
                _buildScreenHeader('Fee Details'),
                const SizedBox(height: 12),
                if (upcoming.isNotEmpty) ...[          
                  const Text('Upcoming Payments', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: Color(0xFF1E1E2D))),
                  const SizedBox(height: 12),
                  _buildUpcomingPayments(upcoming),
                  const SizedBox(height: 20),
                ],
                if (history.isNotEmpty) ...[          
                  const Text('Payment History', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: Color(0xFF1E1E2D))),
                  const SizedBox(height: 12),
                  _buildPaymentHistory(history),
                ],
                if (upcoming.isEmpty && history.isEmpty)
                  const Center(child: Padding(padding: EdgeInsets.only(top: 40), child: Text('No fee records found', style: TextStyle(color: Color(0xFF9E9E9E), fontSize: 16)))),
                const SizedBox(height: 120),
              ],
            ),
          );
        }

        return LayoutBuilder(
          builder: (context, constraints) {
            if (constraints.maxWidth > 900) {
              return SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 24.0),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      flex: 5,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const SizedBox(height: 12),
                          _buildScreenHeader('Fee Details'),
                          const SizedBox(height: 12),
                          _buildOutstandingBalanceCard(data['outstandingBalance']),
                          const SizedBox(height: 20),
                          _buildSummaryCards(data['summary']),
                          const SizedBox(height: 20),
                          _buildPaymentProgress(data['progress']),
                          const SizedBox(height: 20),
                          _buildFeeBreakdown(data['feeBreakdown'], data['progress']['paid'], data['outstandingBalance']['amount']),
                          const SizedBox(height: 120),
                        ],
                      ),
                    ),
                    const SizedBox(width: 24),
                    Expanded(
                      flex: 4,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const SizedBox(height: 24),
                          _buildUpcomingPayments(data['upcomingPayments']),
                          const SizedBox(height: 20),
                          _buildPaymentHistory(data['paymentHistory']),
                          const SizedBox(height: 20),
                          _buildRecentReceipts(data['recentReceipts']),
                          const SizedBox(height: 20),
                          if (data['scholarships'] != null)
                            ...data['scholarships'].map<Widget>((s) => Padding(
                              padding: const EdgeInsets.only(bottom: 20.0),
                              child: _buildScholarshipCard(s),
                            )),
                          _buildFineDetails(data['fineDetails']),
                          const SizedBox(height: 120),
                        ],
                      ),
                    ),
                  ],
                ),
              );
            } else {
              return SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const SizedBox(height: 12),
                    _buildScreenHeader('Fee Details'),
                    const SizedBox(height: 12),
                    _buildOutstandingBalanceCard(data['outstandingBalance']),
                    const SizedBox(height: 20),
                    _buildSummaryCards(data['summary']),
                    const SizedBox(height: 20),
                    _buildPaymentProgress(data['progress']),
                    const SizedBox(height: 20),
                    _buildUpcomingPayments(data['upcomingPayments']),
                    const SizedBox(height: 20),
                    _buildPaymentHistory(data['paymentHistory']),
                    const SizedBox(height: 20),
                    _buildFeeBreakdown(data['feeBreakdown'], data['progress']['paid'], data['outstandingBalance']['amount']),
                    const SizedBox(height: 20),
                    _buildRecentReceipts(data['recentReceipts']),
                    const SizedBox(height: 20),
                    if (data['scholarships'] != null)
                      ...data['scholarships'].map<Widget>((s) => Padding(
                        padding: const EdgeInsets.only(bottom: 20.0),
                        child: _buildScholarshipCard(s),
                      )),
                    _buildFineDetails(data['fineDetails']),
                    const SizedBox(height: 120),
                  ],
                ),
              );
            }
          },
        );
      },
    );
  }

  Widget _buildScreenHeader(String title) {
    return Row(
      children: [
        GestureDetector(
          onTap: () {
            MainLayout.switchTab(0);
          },
          child: Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white,
              shape: BoxShape.circle,
              border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
            ),
            child: const Icon(Icons.arrow_back_rounded, color: Color(0xFF1E1E2D), size: 20),
          ),
        ),
        const SizedBox(width: 16),
        Text(title, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Color(0xFF1E1E2D))),
      ],
    );
  }

  Widget _buildOutstandingBalanceCard(Map<String, dynamic> data) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: const Color(0xFFF9F8FF),
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Outstanding Balance', style: TextStyle(color: Color(0xFF2C2849), fontSize: 15, fontWeight: FontWeight.w900)),
                const SizedBox(height: 8),
                Text('₹${data['amount']}', style: const TextStyle(color: Color(0xFF6C4CF1), fontSize: 24, fontWeight: FontWeight.w900, letterSpacing: -0.5)),
                const SizedBox(height: 12),
                Row(
                  children: [
                    const Icon(Icons.calendar_month_rounded, color: Color(0xFF6C4CF1), size: 18),
                    const SizedBox(width: 6),
                    const Text('Due Date : ', style: TextStyle(color: Color(0xFF4A4A68), fontSize: 14, fontWeight: FontWeight.w600)),
                    Text(data['dueDate'], style: const TextStyle(color: Color(0xFF6C4CF1), fontSize: 14, fontWeight: FontWeight.w900)),
                  ],
                ),
              ],
            ),
          ),
          GestureDetector(
            onTap: () => _showPaymentModal(context, title: 'Tuition Fee', amount: data['amount']),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              decoration: BoxDecoration(
                color: const Color(0xFF6C4CF1),
                borderRadius: BorderRadius.circular(16),
                boxShadow: [
                  BoxShadow(color: const Color(0xFF6C4CF1).withValues(alpha: 0.3), blurRadius: 12, offset: const Offset(0, 4)),
                ],
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: const [
                  Text('Pay Now', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w800, fontSize: 15)),
                  SizedBox(width: 4),
                  Icon(Icons.arrow_forward_rounded, color: Colors.white, size: 18),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _showPaymentModal(BuildContext context, {required String title, required String amount}) {
    showDialog(
      context: context,
      builder: (context) {
        String paymentAmountType = 'full';
        String customAmount = '';
        bool isProcessing = false;
        bool isSuccess = false;

        return Dialog(
          backgroundColor: Colors.transparent,
          insetPadding: const EdgeInsets.all(24),
          child: StatefulBuilder(
            builder: (context, setModalState) {
              return Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(32),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (isSuccess) ...[
                      Container(
                        padding: const EdgeInsets.all(20),
                        decoration: const BoxDecoration(
                          color: Color(0xFFF0FDF4),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.check_rounded, color: Color(0xFF16A34A), size: 48),
                      ),
                      const SizedBox(height: 24),
                      const Text('Payment Successful!', style: TextStyle(fontSize: 22, fontWeight: FontWeight.w900, color: Color(0xFF1E1E2D))),
                      const SizedBox(height: 8),
                      Text('You have successfully paid ${paymentAmountType == 'full' ? '₹$amount' : '₹$customAmount'}.', textAlign: TextAlign.center, style: const TextStyle(fontSize: 14, color: Color(0xFF6C6C80), height: 1.5)),
                      const SizedBox(height: 32),
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton(
                          onPressed: () => Navigator.pop(context),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFF16A34A),
                            foregroundColor: Colors.white,
                            elevation: 0,
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                          ),
                          child: const Text('Done', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                        ),
                      ),
                    ] else if (isProcessing) ...[
                      const SizedBox(height: 32),
                      const CircularProgressIndicator(color: Color(0xFF6C4CF1)),
                      const SizedBox(height: 24),
                      const Text('Processing Payment...', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF1E1E2D))),
                      const SizedBox(height: 32),
                    ] else ...[
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text('Outstanding Balance', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: Color(0xFF1E1E2D))),
                                const SizedBox(height: 6),
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                  decoration: BoxDecoration(color: const Color(0xFFF3F0FF), borderRadius: BorderRadius.circular(4)),
                                  child: Text(title, style: const TextStyle(fontSize: 10, color: Color(0xFF6C4CF1), fontWeight: FontWeight.bold)),
                                ),
                              ],
                            ),
                          ),
                          GestureDetector(
                            onTap: () => Navigator.pop(context),
                            child: const Icon(Icons.close_rounded, color: Color(0xFF1E1E2D), size: 24),
                          ),
                        ],
                      ),
                      const SizedBox(height: 24),
                      const Text('Payment Amount', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF1E1E2D))),
                      const SizedBox(height: 16),
                      Container(
                        padding: const EdgeInsets.all(4),
                        decoration: BoxDecoration(
                          color: const Color(0xFFF8F9FA),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: const Color(0xFFE2E8F0)),
                        ),
                        child: Row(
                          children: [
                            Expanded(
                              child: GestureDetector(
                                onTap: () => setModalState(() => paymentAmountType = 'full'),
                                child: Container(
                                  padding: const EdgeInsets.symmetric(vertical: 10),
                                  decoration: BoxDecoration(
                                    color: paymentAmountType == 'full' ? const Color(0xFF6C4CF1) : Colors.transparent,
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Center(
                                    child: Text('Full', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: paymentAmountType == 'full' ? Colors.white : const Color(0xFF6C6C80))),
                                  ),
                                ),
                              ),
                            ),
                            Expanded(
                              child: GestureDetector(
                                onTap: () => setModalState(() => paymentAmountType = 'custom'),
                                child: Container(
                                  padding: const EdgeInsets.symmetric(vertical: 10),
                                  decoration: BoxDecoration(
                                    color: paymentAmountType == 'custom' ? const Color(0xFF6C4CF1) : Colors.transparent,
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Center(
                                    child: Text('Custom', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: paymentAmountType == 'custom' ? Colors.white : const Color(0xFF6C6C80))),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      if (paymentAmountType == 'custom') ...[
                        const SizedBox(height: 16),
                        TextField(
                          keyboardType: TextInputType.number,
                          decoration: InputDecoration(
                            hintText: 'Enter amount',
                            prefixText: '₹ ',
                            prefixStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF1E1E2D)),
                            filled: true,
                            fillColor: const Color(0xFFF8F9FA),
                            contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(12),
                              borderSide: const BorderSide(color: Color(0xFFE2E8F0)),
                            ),
                            enabledBorder: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(12),
                              borderSide: const BorderSide(color: Color(0xFFE2E8F0)),
                            ),
                            focusedBorder: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(12),
                              borderSide: const BorderSide(color: Color(0xFF6C4CF1), width: 2),
                            ),
                          ),
                          onChanged: (val) {
                            setModalState(() {
                              customAmount = val;
                            });
                          },
                        ),
                      ],
                      const SizedBox(height: 32),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text('Total to Pay', style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Color(0xFF6C6C80))),
                          Text('Pay ${paymentAmountType == 'full' ? '₹$amount' : (customAmount.isEmpty ? '₹0' : '₹$customAmount')}', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF1E1E2D))),
                        ],
                      ),
                      const SizedBox(height: 32),
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton(
                          onPressed: () {
                            setModalState(() => isProcessing = true);
                            Future.delayed(const Duration(seconds: 2), () {
                              if (mounted) {
                                setState(() {
                                  String amt = paymentAmountType == 'full' ? amount : customAmount;
                                  _mockData!['paymentHistory'].insert(0, {
                                    'date': 'Today',
                                    'title': 'Outstanding Balance Paid',
                                    'amount': amt,
                                    'status': 'Success'
                                  });
                                  _mockData!['recentReceipts'].insert(0, {
                                    'receiptNo': 'REC-${Random().nextInt(9000) + 1000}',
                                    'date': 'Today',
                                    'amount': amt
                                  });
                                  
                                  double currentAmt = double.tryParse(amount.replaceAll(',', '')) ?? 0.0;
                                  double paidAmt = double.tryParse(amt.replaceAll(',', '')) ?? 0.0;
                                  double newAmt = currentAmt - paidAmt;
                                  if (newAmt < 0) newAmt = 0;
                                  
                                  // Update formatted amount
                                  String formattedAmt = newAmt.toStringAsFixed(0);
                                  if (formattedAmt.length > 3) {
                                    formattedAmt = '${formattedAmt.substring(0, formattedAmt.length - 3)},${formattedAmt.substring(formattedAmt.length - 3)}';
                                  }
                                  _mockData!['outstandingBalance']['amount'] = formattedAmt;
                                });

                                setModalState(() {
                                  isProcessing = false;
                                  isSuccess = true;
                                });
                              }
                            });
                          },
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFF6C4CF1),
                            foregroundColor: Colors.white,
                            elevation: 0,
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                          ),
                          child: const Text('Pay Now', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                        ),
                      ),
                    ],
                  ],
                ),
              );
            },
          ),
        );
      },
    );
  }


  Widget _buildSummaryCards(List summary) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: summary.map<Widget>((item) {
        Color bgColor;
        Color iconColor;
        IconData icon;
        Color textColor;
        
        if (item['color'] == 'purple') {
          bgColor = const Color(0xFFF8F5FF);
          iconColor = const Color(0xFF6C4CF1);
          textColor = const Color(0xFF1E1E2D);
          icon = Icons.account_balance_wallet_outlined;
        } else if (item['color'] == 'green') {
          bgColor = const Color(0xFFF3FDF7);
          iconColor = const Color(0xFF22C55E);
          textColor = const Color(0xFF1E1E2D);
          icon = Icons.check_circle_outline;
        } else {
          bgColor = const Color(0xFFFFF7F0);
          iconColor = const Color(0xFFF97316);
          textColor = const Color(0xFFF97316); 
          icon = Icons.account_balance_wallet_outlined;
        }
        
        return Expanded(
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 4),
            padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 8),
            decoration: BoxDecoration(
              color: bgColor,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: iconColor.withValues(alpha: 0.1), width: 1.5),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(6),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(color: iconColor.withValues(alpha: 0.15)),
                  ),
                  child: Icon(icon, color: iconColor, size: 18),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(item['type'], style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Color(0xFF1E1E2D))),
                      const SizedBox(height: 2),
                      Text('₹${item['amount']}', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w900, color: textColor), maxLines: 1, overflow: TextOverflow.ellipsis),
                    ],
                  ),
                ),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildPaymentProgress(Map<String, dynamic> progress) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          RichText(
            text: TextSpan(
              text: 'Payment Progress ',
              style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w900, color: Color(0xFF1E1E2D)),
              children: [
                TextSpan(
                  text: '(${progress['year']})',
                  style: const TextStyle(color: Color(0xFF7A7A9D), fontWeight: FontWeight.w600),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: Container(
                  height: 10,
                  decoration: BoxDecoration(
                    color: const Color(0xFFF3EEFF),
                    borderRadius: BorderRadius.circular(5),
                  ),
                  child: FractionallySizedBox(
                    alignment: Alignment.centerLeft,
                    widthFactor: progress['percentage'] / 100,
                    child: Container(
                      decoration: BoxDecoration(
                        color: const Color(0xFF6C4CF1),
                        borderRadius: BorderRadius.circular(5),
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Text('${progress['percentage']}%', style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w900, color: Color(0xFF6C4CF1))),
            ],
          ),
          const SizedBox(height: 8),
          RichText(
            text: TextSpan(
              text: '₹${progress['paid']}',
              style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: Color(0xFF6C4CF1)),
              children: [
                TextSpan(
                  text: ' / ₹${progress['total']}',
                  style: const TextStyle(color: Color(0xFF7A7A9D)),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }



  Widget _buildUpcomingPayments(List payments) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: const [
              Text('Upcoming Payments', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF2C2849))),
              Text('View all', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: Color(0xFF6C4CF1))),
            ],
          ),
          const SizedBox(height: 16),
          ...payments.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            
            Color iconBgColor;
            Color iconColor;
            IconData icon;
            
            switch (item['iconType']) {
              case 'book':
                iconBgColor = const Color(0xFFF4F0FF);
                iconColor = const Color(0xFF6C4CF1);
                icon = Icons.menu_book_rounded;
                break;
              case 'bus':
                iconBgColor = const Color(0xFFFFF7E6);
                iconColor = const Color(0xFFF59E0B);
                icon = Icons.directions_bus_rounded;
                break;
              case 'activity':
                iconBgColor = const Color(0xFFFEF0F5);
                iconColor = const Color(0xFFEC4899);
                icon = Icons.accessibility_new_rounded;
                break;
              default:
                iconBgColor = const Color(0xFFF4F0FF);
                iconColor = const Color(0xFF6C4CF1);
                icon = Icons.circle;
            }
            
            return Column(
              children: [
                if (index != 0)
                  const Divider(color: Color(0xFFF3EEFF), height: 32, thickness: 1.5),
                GestureDetector(
                  onTap: () => _showFeeDetailsModal(item),
                  behavior: HitTestBehavior.opaque,
                  child: Row(
                    children: [
                      Container(
                        width: 52,
                        height: 52,
                        decoration: BoxDecoration(
                          color: iconBgColor,
                          shape: BoxShape.circle,
                        ),
                        child: Icon(icon, color: iconColor, size: 24),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(item['title'], style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800, color: Color(0xFF2C2849))),
                            const SizedBox(height: 4),
                            Text(item['dueDate'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Color(0xFF7A7A9D))),
                          ],
                        ),
                      ),
                      Text('₹${item['amount']}', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFFFF5630))),
                      const SizedBox(width: 12),
                      GestureDetector(
                        onTap: () => _showFeeDetailsModal(item),
                        child: Container(
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            color: const Color(0xFFFFF3F0),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: const Icon(Icons.visibility_outlined, color: Color(0xFFFF5630), size: 20),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            );
          }),
        ],
      ),
    );
  }

  Widget _buildPaymentHistory(List history) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: const [
              Text('Payment History', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF2C2849))),
              Text('View all', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: Color(0xFF6C4CF1))),
            ],
          ),
          const SizedBox(height: 16),
          ...history.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            
            return Column(
              children: [
                if (index != 0)
                  const Divider(color: Color(0xFFF3EEFF), height: 32, thickness: 1.5),
                Row(
                  children: [
                    Container(
                      width: 44,
                      height: 44,
                      decoration: const BoxDecoration(
                        color: Color(0xFFF3FDF7),
                        shape: BoxShape.circle,
                      ),
                      child: Center(
                        child: Container(
                          width: 20,
                          height: 20,
                          decoration: const BoxDecoration(
                            color: Color(0xFF4DBB7E),
                            shape: BoxShape.circle,
                          ),
                          child: const Icon(Icons.check_rounded, color: Colors.white, size: 14),
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(item['date'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Color(0xFF7A7A9D))),
                          const SizedBox(height: 4),
                          Text(item['title'], style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800, color: Color(0xFF2C2849))),
                        ],
                      ),
                    ),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: [
                        Text('₹${item['amount']}', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF2C2849))),
                        const SizedBox(height: 4),
                        Text(item['status'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: Color(0xFF4DBB7E))),
                      ],
                    ),
                    const SizedBox(width: 12),
                    GestureDetector(
                      onTap: () => _showFeeDetailsModal(item),
                      child: Container(
                        padding: const EdgeInsets.all(6),
                        decoration: BoxDecoration(color: const Color(0xFFF4F0FF), borderRadius: BorderRadius.circular(8)),
                        child: const Icon(Icons.visibility_outlined, color: Color(0xFF6C4CF1), size: 20),
                      ),
                    ),
                    const SizedBox(width: 8),
                    GestureDetector(
                      onTap: () => _simulateDownload(item['title'] as String),
                      child: Container(
                        padding: const EdgeInsets.all(6),
                        decoration: BoxDecoration(color: const Color(0xFFF4F0FF), borderRadius: BorderRadius.circular(8)),
                        child: const Icon(LucideIcons.download, color: Color(0xFF6C4CF1), size: 18),
                      ),
                    ),
                  ],
                ),
              ],
            );
          }),
        ],
      ),
    );
  }

  Widget _buildFeeBreakdown(Map<String, dynamic> breakdown, String totalPaidSummary, String outstandingSummary) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Fee Breakdown', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: Color(0xFF1E1B39))),
          const SizedBox(height: 24),
          Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              // Chart
              SizedBox(
                width: 140,
                height: 140,
                child: Stack(
                  alignment: Alignment.center,
                  children: [
                    CustomPaint(
                      size: const Size(140, 140),
                      painter: DonutChartPainter(
                        strokeWidth: 22,
                        segments: (breakdown['items'] as List).map((item) {
                          Color color;
                          switch (item['iconType']) {
                            case 'tuition': color = const Color(0xFF8B5CF6); break;
                            case 'transport': color = const Color(0xFFA1A5B7); break;
                            case 'books': color = const Color(0xFF4ADE80); break;
                            case 'activities': color = const Color(0xFFFB923C); break;
                            case 'uniform': color = const Color(0xFF60A5FA); break;
                            default: color = const Color(0xFF8B5CF6);
                          }
                          double value = double.tryParse(item['amount'].toString().replaceAll(',', '')) ?? 0.0;
                          return {'value': value, 'color': color};
                        }).toList(),
                      ),
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text('₹${breakdown['total']}', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: Color(0xFF1E1B39))),
                        const SizedBox(height: 2),
                        const Text('Total Fees', style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: Color(0xFF7A7A9D))),
                      ],
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 32),
              // Legend
              Expanded(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: (breakdown['items'] as List).map((item) {
                    Color color;
                    switch (item['iconType']) {
                      case 'tuition': color = const Color(0xFF8B5CF6); break;
                      case 'transport': color = const Color(0xFFA1A5B7); break;
                      case 'books': color = const Color(0xFF4ADE80); break;
                      case 'activities': color = const Color(0xFFFB923C); break;
                      case 'uniform': color = const Color(0xFF60A5FA); break;
                      default: color = const Color(0xFF8B5CF6);
                    }
                    String title = item['title'].toString().replaceAll(' Fee', '').replaceAll(' & Material', '');
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: Row(
                        children: [
                          Container(width: 10, height: 10, decoration: BoxDecoration(color: color, shape: BoxShape.circle)),
                          const SizedBox(width: 12),
                          Expanded(child: Text(title, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: Color(0xFF1E1B39)))),
                          Text('₹${item['amount']}', style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: Color(0xFF1E1B39))),
                        ],
                      ),
                    );
                  }).toList(),
                ),
              ),
            ],
          ),
          
          const SizedBox(height: 32),
          

          
          // Total fees bottom row
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
            decoration: BoxDecoration(color: const Color(0xFFF9F8FF), borderRadius: BorderRadius.circular(16)),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text('Total Fees', style: TextStyle(fontSize: 15, fontWeight: FontWeight.w800, color: Color(0xFF6C4CF1))),
                Text('₹${breakdown['total']}', style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w900, color: Color(0xFF6C4CF1))),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildRecentReceipts(List receipts) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: const [
              Text('Recent Receipts', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF2C2849))),
              Text('View all', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: Color(0xFF6C4CF1))),
            ],
          ),
          const SizedBox(height: 16),
          ...receipts.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            
            return Column(
              children: [
                if (index != 0)
                  const Divider(color: Color(0xFFF3EEFF), height: 32, thickness: 1.5),
                Row(
                  children: [
                    Container(
                      width: 48,
                      height: 48,
                      decoration: BoxDecoration(
                        color: const Color(0xFFF4F0FF),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: const Icon(Icons.receipt_long_rounded, color: Color(0xFF6C4CF1), size: 24),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(item['receiptNo'], style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800, color: Color(0xFF2C2849))),
                          const SizedBox(height: 4),
                          Text(item['date'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Color(0xFF7A7A9D))),
                        ],
                      ),
                    ),
                    Text('₹${item['amount']}', style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w900, color: Color(0xFF2C2849))),
                    const SizedBox(width: 12),
                    GestureDetector(
                      onTap: () => _showFeeDetailsModal({
                        ...item,
                        'title': 'Receipt ${item['receiptNo']}',
                        'status': 'Paid'
                      }),
                      child: Container(
                        padding: const EdgeInsets.all(6),
                        decoration: BoxDecoration(color: const Color(0xFFF4F0FF), borderRadius: BorderRadius.circular(8)),
                        child: const Icon(Icons.visibility_outlined, color: Color(0xFF6C4CF1), size: 20),
                      ),
                    ),
                    const SizedBox(width: 8),
                    GestureDetector(
                      onTap: () => _simulateDownload('Receipt ${item['receiptNo']}'),
                      child: Container(
                        padding: const EdgeInsets.all(6),
                        decoration: BoxDecoration(color: const Color(0xFFF4F0FF), borderRadius: BorderRadius.circular(8)),
                        child: const Icon(LucideIcons.download, color: Color(0xFF6C4CF1), size: 18),
                      ),
                    ),
                  ],
                ),
              ],
            );
          }),
        ],
      ),
    );
  }


  Widget _buildFineDetails(Map<String, dynamic> fine) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container(
            width: 52,
            height: 52,
            decoration: BoxDecoration(
              color: const Color(0xFFFFF3F0),
              borderRadius: BorderRadius.circular(12),
            ),
            child: const Icon(Icons.warning_amber_rounded, color: Color(0xFFFF5630), size: 30),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(fine['title'], style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF2C2849))),
                const SizedBox(height: 12),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(fine['type'], style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: Color(0xFF4A4A68))),
                    Text('₹${fine['amount']}', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFFFF5630))),
                  ],
                ),
                const SizedBox(height: 4),
                Text(fine['condition'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Color(0xFF7A7A9D))),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildScholarshipCard(Map<String, dynamic> data) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF3EEFF), width: 1.5),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFFE8E3F8).withValues(alpha: 0.5),
            blurRadius: 15,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container(
            width: 60,
            height: 60,
            decoration: BoxDecoration(
              color: const Color(0xFFEDF8F1), // Light green background
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.workspace_premium_rounded, color: Color(0xFF22C55E), size: 36), // Green badge icon
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(data['status'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: Color(0xFF4A4A68))),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                      decoration: BoxDecoration(
                        color: const Color(0xFFEDF8F1),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        data['pillText'],
                        style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: Color(0xFF22C55E)),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 4),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Expanded(child: Text(data['name'], style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF2C2849)))),
                    Text('₹${data['amount']}', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF22C55E))),
                  ],
                ),
                const SizedBox(height: 4),
                Text(data['description'], style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Color(0xFF7A7A9D))),
              ],
            ),
          ),
        ],
      ),
    );
  }

  void _showFeeDetailsModal(Map<String, dynamic> item) {
    showDialog(
      context: context,
      builder: (context) {
        return Dialog(
          backgroundColor: Colors.transparent,
          insetPadding: const EdgeInsets.all(24),
          child: Container(
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: const Color(0xFFF8F9FA),
              borderRadius: BorderRadius.circular(32),
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
              
              // Main Ticket Card
              Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(24),
                  boxShadow: [
                    BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 20, offset: const Offset(0, 10)),
                  ],
                ),
                child: Column(
                  children: [
                    // Top Gradient Section
                    Container(
                      padding: const EdgeInsets.all(24),
                      decoration: const BoxDecoration(
                        gradient: LinearGradient(
                          colors: [Color(0xFF6C4CF1), Color(0xFF8B73F5)],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
                      ),
                      child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(
                              color: Colors.white.withValues(alpha: 0.2),
                              borderRadius: BorderRadius.circular(16),
                            ),
                            child: const Icon(Icons.receipt_long_rounded, color: Colors.white, size: 28),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text('FEE DETAILS', style: TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
                                const SizedBox(height: 4),
                                Text(item['title'] ?? 'Fee Payment', style: const TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.w900)),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    
                    // Dashed Divider Area
                    Stack(
                      children: [
                        const Divider(color: Color(0xFFE2E8F0), thickness: 2, height: 2),
                        Positioned(
                          left: -10,
                          top: -10,
                          child: Container(width: 20, height: 20, decoration: const BoxDecoration(color: Color(0xFFF8F9FA), shape: BoxShape.circle)),
                        ),
                        Positioned(
                          right: -10,
                          top: -10,
                          child: Container(width: 20, height: 20, decoration: const BoxDecoration(color: Color(0xFFF8F9FA), shape: BoxShape.circle)),
                        ),
                      ],
                    ),
                    
                    // Bottom Info Section
                    Padding(
                      padding: const EdgeInsets.all(24),
                      child: Column(
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(item['dueDate'] != null ? 'Due Date' : 'Date', style: const TextStyle(fontSize: 13, color: Color(0xFF6C6C80), fontWeight: FontWeight.w600)),
                                  const SizedBox(height: 4),
                                  Text(item['dueDate'] ?? item['date'] ?? 'Unknown', style: const TextStyle(fontSize: 15, color: Color(0xFF1E1E2D), fontWeight: FontWeight.bold)),
                                ],
                              ),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.end,
                                children: [
                                  const Text('Status', style: TextStyle(fontSize: 13, color: Color(0xFF6C6C80), fontWeight: FontWeight.w600)),
                                  const SizedBox(height: 4),
                                  Container(
                                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                    decoration: BoxDecoration(
                                      color: (item['status'] == 'Paid' || item['status'] == 'Completed' || item['status'] == 'Success') ? const Color(0xFFF3FDF7) : const Color(0xFFFFF3F0), 
                                      borderRadius: BorderRadius.circular(6),
                                    ),
                                    child: Text(item['status'] ?? 'Pending', style: TextStyle(fontSize: 12, color: (item['status'] == 'Paid' || item['status'] == 'Completed' || item['status'] == 'Success') ? const Color(0xFF4DBB7E) : const Color(0xFFFF5630), fontWeight: FontWeight.bold)),
                                  ),
                                ],
                              ),
                            ],
                          ),
                          const SizedBox(height: 24),
                          Container(
                            padding: const EdgeInsets.all(16),
                            decoration: BoxDecoration(
                              color: const Color(0xFFF4F0FF),
                              borderRadius: BorderRadius.circular(16),
                            ),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                const Text('Total Amount', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, color: Color(0xFF6C4CF1))),
                                Text('₹${item['amount']}', style: const TextStyle(fontSize: 24, fontWeight: FontWeight.w900, color: Color(0xFF1E1E2D))),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 32),
              
              // Action Buttons (Pay Now / Download PDF & Close)
              Row(
                children: [
                  if (item['status'] == 'Paid' || item['status'] == 'Success' || item['receiptNo'] != null)
                    Expanded(
                      child: ElevatedButton.icon(
                        onPressed: () {
                          Navigator.pop(context);
                          _simulateDownload(item['title'] ?? 'Receipt');
                        },
                        icon: const Icon(LucideIcons.download, size: 18),
                        label: const Text('Download PDF', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF6C4CF1),
                          foregroundColor: Colors.white,
                          elevation: 0,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                        ),
                      ),
                    )
                  else
                    Expanded(
                      child: ElevatedButton.icon(
                        onPressed: () {
                          Navigator.pop(context);
                          _showPaymentModal(context, title: item['title'] ?? 'Fee Payment', amount: item['amount'] ?? '0');
                        },
                        icon: const Icon(Icons.payment_rounded, size: 18),
                        label: const Text('Pay Now', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF6C4CF1),
                          foregroundColor: Colors.white,
                          elevation: 0,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                        ),
                      ),
                    ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: () => Navigator.pop(context),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFFF4F0FF),
                        foregroundColor: const Color(0xFF6C4CF1),
                        elevation: 0,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                      ),
                      child: const Text('Close', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
            ],
          ),
        ),
        );
      },
    );
  }
}

class DonutChartPainter extends CustomPainter {
  final List<Map<String, dynamic>> segments;
  final double strokeWidth;

  DonutChartPainter({required this.segments, this.strokeWidth = 24});

  @override
  void paint(Canvas canvas, Size size) {
    double total = segments.fold(0.0, (sum, item) => sum + (item['value'] as double));
    double startAngle = -pi / 2;
    
    final rect = Rect.fromLTWH(strokeWidth / 2, strokeWidth / 2, size.width - strokeWidth, size.height - strokeWidth);

    for (var segment in segments) {
      if (segment['value'] == 0) continue;
      
      final sweepAngle = (segment['value'] as double) / total * 2 * pi;
      final paint = Paint()
        ..color = segment['color'] as Color
        ..style = PaintingStyle.stroke
        ..strokeWidth = strokeWidth
        ..strokeCap = StrokeCap.butt;
        
      canvas.drawArc(rect, startAngle, sweepAngle, false, paint);
      startAngle += sweepAngle;
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
